name: Publish Docker Image App

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: dkfz-unite/unite-commands
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish web app
        run: sh publish-linux-x64.sh
      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish/linux-x64
    
  build-and-push-image:
    needs: build-and-publish-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove old web app
        run: rm -r app
      - name: Copy new web app
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./app
      - name: Make web app executable
        run: chmod a+rx ./app/commands
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            USER=${{ github.actor }}
            TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ${{env.REGISTRY}}/${{github.repository}}
